### ISSUE TITLE
Loading circus web results in an AssertionError

### ISSUE THREAD

**Issue by ohlookemus** [circus-tent/circus-web#66]
When I try to connect to an instance I'm getting. Not sure what exactly I'm doing wrong.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1613, in future_complete
    f.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/site-packages/circusweb/circushttpd.py", line 164, in post
    endpoints = self.get_arguments('endpoint_list', [])
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 394, in get_arguments
    assert isinstance(strip, bool)
AssertionError
```

My circus.ini

```
[socket:web]
host = 0.0.0.0
port = 8000

[watcher:web]
cmd = chaussette test.wsgi.application
args = --fd $(circus.sockets.web) --backend gevent
working_dir = /usr/src/app
copy_env = True
use_sockets = True
numprocesses = 2

[circus]
httpd = True
httpd_host = 0.0.0.0
httpd_port = 8050
statsd = True
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
stats_endpoint = tcp://127.0.0.1:5557
```

nginx config:
```
server {

    listen 0.0.0.0:80;
    server_name circus.test.com;
    charset utf-8;

    location / {
        proxy_pass http://web:8050;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_redirect off;
    }

    location ~/media/\*(.png|.jpg|.css|.js|.ico)$ {
        alias /usr/local/lib/python2.7/site-packages/circusweb/media;
    }

}
```

**Comment by ohlookemus** [comment]
Duplicate of https://github.com/circus-tent/circus-web/issues/59
